### PR TITLE
Using correct journald fields, mapping priorities, sending defaults.

### PR DESCRIPTION
**Pull request by nstielau**
This updates the winston transport to use the correct `MESSAGE` field.  Additionally, this adds the ability to specify default key/value pairs on transport creation (i.e. SYSLOG_IDENTIFIER), and attempts to map the `level` string passed by winston into a numerical value for the journald PRIORITY field.

### CODE REVIEW

**Comment by joemiller** [comment]
+1

**Comment by marktheunissen** [comment]
Cool, thanks!

**Comment by nstielau** [comment]
Awesome, thanks @marktheunissen.  I heard you were traveling around, and hoping you'd get a chance to take a peek.  Do you think you could push 0.0.3 to NPM? Thanks!

**Comment by marktheunissen** [comment]
Yeah I have been traveling, sorry for the delay. Should be pushed now, although the website isn't updated but it looked like it succeeded. Let me know if I've missed something, haven't used NPM in a while.

**Pull request merged**
